### ISSUE TITLE
dev:weapp 报错

### ISSUE THREAD

**Issue by whqgo** [jsLyLeeHi/taro-react#1]
拉去项目 yarn 执行 dev:weapp

./src/app.tsx
Module build failed (from ./loaders/injectComponent/index.js):
TypeError: schemaUtils.validate is not a function

监听文件修改中...

./src/app.tsx
Module build failed (from ./loaders/injectComponent/index.js):
TypeError: schemaUtils.validate is not a function
    at Object.index (D:\project\weixin\taro-react\loaders\src\index.ts:30:3),./src/pages/tabbar/serve/index.tsx
Module build failed (from ./loaders/injectComponent/index.js):
TypeError: schemaUtils.validate is not a function
    at Object.index (D:\project\weixin\taro-react\loaders\src\index.ts:30:3),./src/pages/tabbar/index/index.tsx
Module build failed (from ./loaders/injectComponent/index.js):
TypeError: schemaUtils.validate is not a function
    at Object.index (D:\project\weixin\taro-react\loaders\src\index.ts:30:3),./src/pages/tabbar/mine/index.tsx
Module build failed (from ./loaders/injectComponent/index.js):
TypeError: schemaUtils.validate is not a function
    at Object.index (D:\project\weixin\taro-react\loaders\src\index.ts:30:3),./src/pages/tool/richTextPage/index.tsx
Module build failed (from ./loaders/injectComponent/index.js):
TypeError: schemaUtils.validate is not a function
    at Object.index (D:\project\weixin\taro-react\loaders\src\index.ts:30:3),./src/pages/user/login/index.tsx
Module build failed (from ./loaders/injectComponent/index.js):
TypeError: schemaUtils.validate is not a function
    at Object.index (D:\project\weixin\taro-react\loaders\src\index.ts:30:3),./src/pages/tool/imagePreview/index.tsx
Module build failed (from ./loaders/injectComponent/index.js):
TypeError: schemaUtils.validate is not a function
    at Object.index (D:\project\weixin\taro-react\loaders\src\index.ts:30:3),./src/pages/tool/webViewPage/index.tsx
Module build failed (from ./loaders/injectComponent/index.js):
TypeError: schemaUtils.validate is not a function
    at Object.index (D:\project\weixin\taro-react\loaders\src\index.ts:30:3)

node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Array]".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by jsLyLeeHi** [comment]
你用npm装啊
